name: Continuous integration

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: x86_64-pc-windows-gnu
            os: windows-latest
            file: surreal-${{ github.ref_name }}.windows-amd64
    runs-on: ${{ matrix.os }}
    env:
      # OPENSSL_STATIC: true
      OPENSSL_NO_VENDOR: false
    steps:
        
      - name: Install choco
        if: ${{ contains(matrix.os, 'windows') }}
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install pacman

      - name: Install dependencies
        if: ${{ contains(matrix.os, 'windows') }}
        run: pacman -S openssl openssl-devel pkg-config
        
      # - run: vcpkg install openssl:x64-windows
      
      - run: pacman -S mingw-w64-x86_64-openssl
      
      # - run: set VCPKG_ROOT=c:\path\to\vcpkg\installation
      
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          repository: 'surrealdb/surrealdb'

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.arch }}

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.arch }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AMAZON_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AMAZON_SECRET_KEY }}

      - name: Package binaries
        shell: bash
        run: |
          cd target/${{ matrix.arch }}/release
          cp surreal.exe ${{ matrix.file }}.exe
          echo $(shasum -a 256 ${{ matrix.file }}.exe | cut -f1 -d' ') > ${{ matrix.file }}.txt
          aws s3 cp --cache-control 'no-store' ${{ matrix.file }}.exe s3://download.surrealdb.com/${{ github.ref_name }}/
          aws s3 cp --cache-control 'no-store' ${{ matrix.file }}.txt s3://download.surrealdb.com/${{ github.ref_name }}/
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.file }}
          path: |
            target/${{ matrix.arch }}/release/surreal
            target/${{ matrix.arch }}/release/${{ matrix.file }}.tgz
            target/${{ matrix.arch }}/release/${{ matrix.file }}.txt
            target/${{ matrix.arch }}/release/${{ matrix.file }}.exe
